### ISSUE TITLE
[Bug] gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by cathaysia** [qier222/YesPlayMusic#1035]
Fedora 35 桌面端 Bug

此 Bug 已被查明：https://ask.fedoraproject.org/t/all-chromium-based-apps-crashing-with-gpu-related-messages-after-recent-upgrade/16201/4

但是需要修复

大概意思是由于 Glib3 中使用了 clone 系统调用，但是 Chrome 沙箱不允许此调用导致的系统崩溃

完整的日志为：

```
[background.js] initializing
[background.js] creating express app
(node:11362) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `yesplaymusic --trace-deprecation ...` to show where the warning was created)
[NetEase API] server running @ http://127.0.0.1:10754
Gtk-Message: 13:36:30.877: Failed to load module "appmenu-gtk-module"
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
APPIMAGE env is not defined, current application is not an AppImage
(node:11362) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:11362) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setMenu' of undefined
    at App.<anonymous> (/opt/YesPlayMusic/resources/app.asar/background.js:2:2247740)
    at App.emit (events.js:315:20)
(node:11362) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11362) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11362) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.a (/opt/YesPlayMusic/resources/app.asar/background.js:2:2106695)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:11362) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[11362:1105/133633.026836:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  yesplaymusic
```

**Comment by memorydream** [comment]
看上去升级electron包可以解决这个问题？你fork repo然后测试一下？我这里是arch，没有这个问题，没办法进行相关的测试

**Comment by cathaysia** [comment]
我手动将 package 中 electron 中的版本号改成了 15.3.0，然后执行

```
yarn install
yarn build
yarn electron:build --linux rpm:x64
```

强两步都成功了，但是第三步输出了大量的日志，之后失败了
[Uploading 1.log…]()

**Comment by memorydream** [comment]
https://github.com/memorydream/YesPlayMusic/releases/tag/v0.4.2-e13.6.1
尝试升级了一下，你试试行不行

**Comment by cathaysia** [comment]
我又下载了崩溃版本的appimage作为对比
新提供的版本可以正常运行
旧版本的appimage会出现相同的错误
看来升级electron可以解决这个错误:)
________________________________
