### ISSUE TITLE
手动构建出错

### ISSUE THREAD

**Issue by xiaozhangup** [qier222/YesPlayMusic#1099]
C:\Users\Adminisrator\Desktop\YesPlayMusic>node -v
v14.18.2

C:\Users\Adminisrator\Desktop\YesPlayMusic>yarn -v
1.22.17

报错如下

yarn run v1.22.17ator\Desktop\YesPlayMusic>yarn electron:build --linux deb:x64
$ vue-cli-service electron:build -p never --linux deb:x64
 INFO  Bundling render process:

|  Building modern bundle for production...

 DONE  Compiled successfully in 27704ms                                                                      下午8:57:12

  File                                                          Size                       Gzipped

  dist_electron\bundled\js\chunk-vendors.0cddbead.js            503.74 KiB                 160.21 KiB
  dist_electron\bundled\js\index.62abb393.js                    142.72 KiB                 41.03 KiB
  dist_electron\bundled\js\chunk-50523553.3d1dd103.js           121.74 KiB                 34.71 KiB
  dist_electron\bundled\js\chunk-ace8f16e.37a5a0d2.js           85.32 KiB                  29.21 KiB
  dist_electron\bundled\js\chunk-4bbc70da.c72f920f.js           38.39 KiB                  13.33 KiB
  dist_electron\bundled\js\chunk-5474e0a6.7bb4ac3f.js           35.07 KiB                  10.41 KiB
  dist_electron\bundled\js\chunk-a550b388.f2998c36.js           17.71 KiB                  5.11 KiB
  dist_electron\bundled\js\chunk-370f106e.a129af6b.js           16.47 KiB                  5.16 KiB
  dist_electron\bundled\js\chunk-7afbbd6e.427d9bbc.js           15.85 KiB                  4.70 KiB
  dist_electron\bundled\js\chunk-b3e0bd3c.772fa78d.js           15.31 KiB                  4.86 KiB
  dist_electron\bundled\js\chunk-1bed28ec.a3c30bd5.js           14.60 KiB                  4.77 KiB
  dist_electron\bundled\js\chunk-40c9b056.165f4873.js           13.29 KiB                  4.17 KiB
  dist_electron\bundled\js\chunk-7764825e.dbb3d222.js           13.10 KiB                  4.46 KiB
  dist_electron\bundled\js\chunk-032c8449.4f0b3ad5.js           12.04 KiB                  4.03 KiB
  dist_electron\bundled\precache-manifest.6153848c73b232518f    7.50 KiB                   1.91 KiB
  b038a0e3cb3637.js
  dist_electron\bundled\js\chunk-7f28686c.33d59aaa.js           6.76 KiB                   2.46 KiB
  dist_electron\bundled\js\chunk-269b39c4.2d14fe13.js           5.41 KiB                   2.19 KiB
  dist_electron\bundled\js\chunk-0f7b5faa.a1718a83.js           4.52 KiB                   1.81 KiB
  dist_electron\bundled\js\chunk-0db2d828.03d2a59d.js           3.26 KiB                   1.35 KiB
  dist_electron\bundled\js\chunk-44d086a7.f3397f5e.js           2.03 KiB                   1.11 KiB
  dist_electron\bundled\js\chunk-d2c8691e.9ae20010.js           1.76 KiB                   0.70 KiB
  dist_electron\bundled\js\chunk-b10ef4b6.b05a06b2.js           1.49 KiB                   0.84 KiB
  dist_electron\bundled\service-worker.js                       1.05 KiB                   0.62 KiB
  dist_electron\bundled\css\chunk-50523553.b1450359.css         37.14 KiB                  5.69 KiB
  dist_electron\bundled\css\index.2fb6136e.css                  27.26 KiB                  5.36 KiB
  dist_electron\bundled\css\chunk-vendors.c5cef460.css          17.14 KiB                  3.45 KiB
  dist_electron\bundled\css\chunk-370f106e.46d705af.css         8.91 KiB                   2.02 KiB
  dist_electron\bundled\css\chunk-a550b388.011f3372.css         7.63 KiB                   1.72 KiB
  dist_electron\bundled\css\chunk-7afbbd6e.c8d4c36c.css         6.79 KiB                   1.61 KiB
  dist_electron\bundled\css\chunk-b3e0bd3c.359c0794.css         6.33 KiB                   1.62 KiB
  dist_electron\bundled\css\chunk-5474e0a6.e0d3f36a.css         5.46 KiB                   1.34 KiB
  dist_electron\bundled\css\chunk-1bed28ec.a1ec2049.css         5.08 KiB                   1.30 KiB
  dist_electron\bundled\css\chunk-032c8449.1ff439c6.css         4.90 KiB                   1.27 KiB
  dist_electron\bundled\css\chunk-7764825e.d6cf6181.css         4.78 KiB                   1.24 KiB
  dist_electron\bundled\css\chunk-40c9b056.e6384f91.css         4.69 KiB                   1.25 KiB
  dist_electron\bundled\css\chunk-ace8f16e.a52fdc22.css         3.88 KiB                   0.96 KiB
  dist_electron\bundled\css\chunk-4bbc70da.c268d7db.css         3.24 KiB                   0.88 KiB
  dist_electron\bundled\css\chunk-7f28686c.e16bee2b.css         2.58 KiB                   0.86 KiB
  dist_electron\bundled\css\chunk-0f7b5faa.02b2a624.css         2.29 KiB                   0.65 KiB
  dist_electron\bundled\css\chunk-269b39c4.0b5d1add.css         2.24 KiB                   0.77 KiB
  dist_electron\bundled\css\chunk-b10ef4b6.1fdf5d5e.css         1.45 KiB                   0.46 KiB
  dist_electron\bundled\css\chunk-d2c8691e.d21ac2a1.css         1.20 KiB                   0.46 KiB
  dist_electron\bundled\css\chunk-44d086a7.f8604c20.css         0.77 KiB                   0.36 KiB
  dist_electron\bundled\css\chunk-0db2d828.c5b60726.css         0.45 KiB                   0.26 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron\bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

|  Bundling main process...

 WARNING  Compiled with 3 warnings                                                                           下午8:57:20

 warning  in ./node_modules/discord-rpc/node_modules/ws/lib/buffer-util.js

Module not found: Error: Can't resolve 'bufferutil' in 'C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\discord-rpc\node_modules\ws\lib'

 warning  in ./node_modules/discord-rpc/src/util.js

Module not found: Error: Can't resolve 'register-scheme' in 'C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\discord-rpc\src'

 warning  in ./node_modules/discord-rpc/node_modules/ws/lib/validation.js

Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\discord-rpc\node_modules\ws\lib'

  File                                   Size                                  Gzipped

  dist_electron\bundled\background.js    2329.20 KiB                           766.97 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=10.0.19043
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=13.0.1 appOutDir=dist_electron\linux-unpacked
  • scheduling remote build  target=deb arch=x64
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1grjphp": x509: certificate signed by unknown authority attempt=0 waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1grjphp": x509: certificate signed by unknown authority attempt=1 waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1grjphp": x509: certificate signed by unknown authority attempt=2 waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1grjphp": x509: certificate signed by unknown authority
ExecError: C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\app-builder-bin\win\ia32\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\builder-util\src\util.ts:243:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
From previous event:
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at RemoteBuilder.build (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:52:28)
    at RemoteTarget.finishBuild (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\app-builder-lib\src\linuxPackager.ts:99:30)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
    at Packager.doBuild (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\app-builder-lib\src\packager.ts:446:5)
    at executeFinally (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\app-builder-lib\src\packager.ts:369:31)
    at Packager.build (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\app-builder-lib\src\packager.ts:333:12)
    at executeFinally (C:\Users\Adminisrator\Desktop\YesPlayMusic\node_modules\builder-util\src\promise.ts:12:14) {
  exitCode: 1,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by xiaozhangup** [comment]
已通过更换系统解决问题
