### ISSUE TITLE
自动播放歌曲切下一首后弹出错误代码

### ISSUE THREAD

**Issue by KiWinger** [qier222/YesPlayMusic#1222]
### 反馈 bug 需要的信息

- 用的是是客户端0.4.3
- 电脑操作系统Win10 21H2
- 控制台 Console 页面的截图
![20220111145426](https://user-images.githubusercontent.com/49084827/148895513-577db2b7-0bcf-46fa-a384-3fd245906a8c.png)

自动播放收藏歌单歌曲时，自动切下一首后，立马弹出错误代码，如下
Uncaught Exception:
Error: EBADF: bad file descriptor, write
    at Object.writeSync (fs.js:711:3)
    at actualWrite (C:\Users\xxx\AppData\Local\Temp\23BANIm2bwnMXexivnOH8RacOMK\resources\app.asar\node_modules\sonic-boom\index.js:349:26)
    at SonicBoom.write (C:\Users\xxx\AppData\Local\Temp\23BANIm2bwnMXexivnOH8RacOMK\resources\app.asar\node_modules\sonic-boom\index.js:218:5)
    at Object.write (C:\Users\xxx\AppData\Local\Temp\23BANIm2bwnMXexivnOH8RacOMK\resources\app.asar\node_modules\pino\lib\tools.js:286:12)
    at Pino.write (C:\Users\xxx\AppData\Local\Temp\23BANIm2bwnMXexivnOH8RacOMK\resources\app.asar\node_modules\pino\lib\proto.js:213:15)
    at Pino.LOG [as warn] (C:\Users\xxx\AppData\Local\Temp\23BANIm2bwnMXexivnOH8RacOMK\resources\app.asar\node_modules\pino\lib\tools.js:55:21)
    at ClientRequest.<anonymous> (C:\Users\xxx\AppData\Local\Temp\23BANIm2bwnMXexivnOH8RacOMK\resources\app.asar\node_modules\@unblockneteasemusic\server\src\request.js:119:12)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:784:9)

**Comment by memorydream** [comment]
#1145 重复
