### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by keeeeevin-123** [qier222/YesPlayMusic#1379]
Error
×
A JavaScript error occurred in the main process
Uncaught Exception:
Error:EBADF:bad file descriptor,write
at Object.writeSync (fs.js:711:3)
at actualWrite(C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\sonic-boom\index.js:349:26)
at SonicBoom.write(C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\sonic-boom\index.js:218:5)
at Object.write(C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\pino\lib\tools.js:286:12)
at Pino.write(C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\pino\lib\proto.js:213:15)
at Pino.LOG [as warn](C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\pino\lib\tools.js:55:21)
at ClientRequest.<anonymous>(C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\@unblockneteasemusic\...:12)
at Object.onceWrapper(events.js:421:28)
at ClientRequest.emit(events.js:315:20)
at Socket.emitRequestTimeout(_http_client.js:784:9)
确定
win11    0.43有，更新了0.44还是有

**Comment by keeeeevin-123** [comment]
哦 ，已经有人说了，关了
