### ISSUE TITLE
(node:7041) UnhandledPromiseRejectionWarning: Error: Could not connect

### ISSUE THREAD

**Issue by shenghuang147** [qier222/YesPlayMusic#1769]
# 使用环境即版本信息
+ `YesPlayMusic 版本`：`V0.4.5 客户端`
+ `操作系统`：`OpenSuse Leap 15.4 X86_64`

# 说明
启动后一直在跑进度条，如下图
![图片](https://user-images.githubusercontent.com/65714801/184016844-a59db120-c66a-453f-ab7c-834c055b337e.png)

`F12` 截图

![图片](https://user-images.githubusercontent.com/65714801/184017192-dcb7239b-d7d2-4bf5-8669-2e3c8a6f720f.png)

![图片](https://user-images.githubusercontent.com/65714801/184017048-e5702c9e-612f-4518-be7d-10245d169ae4.png)

我看日志可能是后端没启动起来，但是不知道要怎么解决

# 日志
``````bash
[background.js] initializing
[NetEase API] initiating NCM API
[background.js] creating express app
(node:7041) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `yesplaymusic --trace-deprecation ...` to show where the warning was created)
server running @ http://AsusServer:10754
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
APPIMAGE env is not defined, current application is not an AppImage
[globalShortcut.js] registerGlobalShortcut
checkForUpdatesAndNotify called, downloadPromise is null
(node:7041) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.a (/usr/lib/yesplaymusic/resources/app.asar/background.js:2:2444038)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:7041) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7041) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[background.js] window ready-to-show event
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

``````

**Comment by shenghuang147** [comment]
已解决
原因：我修改了 `hostname`，导致无法 `127.0.0.1` 无法解析到我的 `hostname`

https://github.com/qier222/YesPlayMusic/issues/1637#issuecomment-1139360607

**Comment by shenghuang147** [comment]
已解决
原因：我修改了 `hostname`，导致无法 `127.0.0.1` 无法解析到我的 `hostname`

https://github.com/qier222/YesPlayMusic/issues/1637#issuecomment-1139360607
