### ISSUE TITLE
网页版啥也加载不出来

### ISSUE THREAD

**Issue by XuuChannel** [qier222/YesPlayMusic#1927]
部署在docker上的网页版
日志中输出类似以下信息：

[ERR] /personalized? Limit=10&realIP=211.161.244.70 {
status: 502,
body: {
code: 502,
msg: AxiosError: connect ETIMEDOUT 103.126.92.133:443
at Function.AxiosError.from (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:789:14)
at RedirectableRequest.handleRequestError (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:2744:25)
at RedirectableRequest.emit (node:events:513:28)
at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/follow-redirects/index.js:14:24)
at ClientRequest.emit (node:events:513:28)
at TLSSocket.socketErrorListener (node:_http_client:481:9)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
port: 443,
address: '103.126.92.133',
syscall: 'connect',
code: 'ETIMEDOUT',
errno: -110,
config: [Object],
request: [Writable],
cause: [Error]
}
}
}

看起来像是连接哪个服务器失败了 是哪里出问题了？

**Comment by 333brt** [comment]
code: 'ETIMEDOUT',
这个应该是连接超时
可能是网络问题
