### ISSUE TITLE
【bug-v2.0.0-alpha-2】播放音乐，点击流动图标出错，UI界面发生更改

### ISSUE THREAD

**Issue by Guugie** [qier222/YesPlayMusic#2023]
当前操作系统：Windows 10
运行版本：R3PLAY v2.0.0-alpha-2 客户端

描述：
未登录账号，播放音乐，点击查看合集，然后点击流动图标出错，UI界面发生更改

客户端，按F12没用

UI界面与错误查询
<img width="968" alt="屏幕截图 2023-04-02 210940" src="https://user-images.githubusercontent.com/32669827/229355144-cad2b37a-a8bf-4b58-9be1-c4f1b4d3b5e2.png">
<img width="1072" alt="屏幕截图 2023-04-02 211009" src="https://user-images.githubusercontent.com/32669827/229355147-090e8d55-faea-4f5e-b2e5-6b94918ab687.png">

以下是子窗口信息（注：以下信息中，抹去了端口号，localhost:XXX 改为 localhost:PROT）
at zO (http://localhost:PROT/assets/index-45d98636.js:66:4439)
at JO (http://localhost:PROT/assets/index-45d98636.js:66:6590)
at Vp (http://localhost:PROT/assets/index-45d98636.js:311:154)
at Et (http://localhost:PROT/assets/index-45d98636.js:311:878)
at rY (http://localhost:PROT/assets/index-45d98636.js:326:4043)
at div
at main
at NU (http://localhost:PROT/assets/index-45d98636.js:303:83581)
at s (http://localhost:PROT/assets/index-45d98636.js:303:84000)
at sY (http://localhost:PROT/assets/index-45d98636.js:326:5159)
at div
at zK (http://localhost:PROT/assets/index-45d98636.js:431:6358)
at ug (http://localhost:PROT/assets/index-45d98636.js:95:2679)
at WK (http://localhost:PROT/assets/index-45d98636.js:433:185)
at XK
at PD (http://localhost:PROT/assets/index-45d98636.js:109:1203)
at KO (http://localhost:PROT/assets/index-45d98636.js:66:6026)
at nA (http://localhost:PROT/assets/index-45d98636.js:75:713)
Reload

**Comment by SingYann** [comment]
同错误 ArchLinux+LinuxZen 6.2.10+KDE5.27.4

**Comment by SingYann** [comment]
同错误 ArchLinux+Linux zen 6.2.10+KDE 5.27.4
