### ISSUE TITLE
"Cannot find module" error when trying to run ./YesPlayMusic-0.4.8.AppImage

### ISSUE THREAD

**Issue by CocoNautty** [qier222/YesPlayMusic#2189]
I'm on openSUSE 15.5, and I have failed to run the 0.4.8 version AppImage.

Full command and its outputs are as follows:
```
$ ./YesPlayMusic-0.4.8.AppImage 
/usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@unblockneteasemusic/rust-napi-linux-x64-gnu'
Require stack:
- /tmp/.mount_YesPlao8Iryh/resources/app.asar/node_modules/@unblockneteasemusic/rust-napi/index.js
- /tmp/.mount_YesPlao8Iryh/resources/app.asar/background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_YesPlao8Iryh/resources/app.asar/node_modules/@unblockneteasemusic/rust-napi/index.js:184:31)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

```

**Comment by CocoNautty** [comment]
okay, that problem has been solved. but now I encountered a new issue:
```
$ ./YesPlayMusic-0.4.8.AppImage --trace-warnings
/usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
[background.js] initializing
[NetEase API] initiating NCM API
[background.js] creating express app
server running @ http://localhost.localdomain:10754
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
Checking for update
libva error: /usr/lib64/dri/i965_drv_video.so init failed
[globalShortcut.js] registerGlobalShortcut
(node:27687) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.o (/tmp/.mount_YesPla3Yg54M/resources/app.asar/background.js:2:3084317)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `yesplaymusic --trace-warnings ...` to show where the warning was created)
(node:27687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[background.js] window ready-to-show event
Update for version 0.4.8 is not available (latest version: 0.4.8, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null

```

**Comment by pan93412** [comment]
You might need to install your display card driver.

**Comment by CocoNautty** [comment]
After updating to 0.4.8-2, the appimage is now functioning well without any black screen or failure, but the warning persists if I run it through terminal. 

Maybe it's a minor problem since it now won't affect my use, but I'm quite sure that I've got my display driver right.
