### ISSUE TITLE
0.4.8-1用不了啊，报错如下

### ISSUE THREAD

**Issue by xinwf** [qier222/YesPlayMusic#2191]
[background.js] initializing
[NetEase API] initiating NCM API
[background.js] creating express app
server running @ http://localhost:10754
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
Checking for update
[globalShortcut.js] registerGlobalShortcut
(node:15962) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.o (/tmp/.mount_YesPlaUoUyzX/resources/app.asar/background.js:2:3084317)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `yesplaymusic --trace-warnings ...` to show where the warning was created)
(node:15962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[background.js] window ready-to-show event
Update for version 0.4.8 is not available (latest version: 0.4.8, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null

**Comment by rainbowflesh** [comment]
Duplicate & probably fixed in #2190
