### ISSUE TITLE
Error: Tried to write a message to a closed stream

### ISSUE THREAD

**Issue by zayn7lie** [qier222/YesPlayMusic#2204]
正常使用 yesplaymusic 時突然出現以下報錯，關掉後反覆彈出：
![photo_2024-03-14_09-18-43](https://github.com/qier222/YesPlayMusic/assets/74305747/19831794-3b7e-48cf-a4ee-e386b460242a)

```
$ yesplaymusic
[background.js] initializing
[NetEase API] initiating NCM API
[background.js] creating express app
server running @ http://localhost:10754
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
Checking for update
[globalShortcut.js] registerGlobalShortcut
(node:1809) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.o (/tmp/.mount_YesPlaqnf5RQ/resources/app.asar/background.js:2:3081497)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `yesplaymusic --trace-warnings ...` to show where the warning was created)
(node:1809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[background.js] window ready-to-show event
Update for version 0.4.8 is not available (latest version: 0.4.8, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
^C^C
```

```
$ neofetch
                   -`                    zayn7lie@zayn7lie-acl 
                  .o+`                   --------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: XPS 13 9310 2-in-1 
               `+oooooo:                 Kernel: 6.7.9-arch1-1 
               -+oooooo+:                Uptime: 6 mins 
             `/:-:++oooo+:               Packages: 769 (pacman) 
            `/++++/+++++++:              Shell: bash 5.2.26 
           `/++++++++++++++:             Resolution: 1920x1200 
          `/+++ooooooooooooo/`           WM: Hyprland 
         ./ooosssso++osssssso+`          Terminal: kitty 
        .oossssso-````/ossssss+`         CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
       -osssssso.      :ssssssso.        GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
      :osssssss/        osssso+++.       Memory: 3558MiB / 15709MiB 
     /ossssssss/        +ssssooo/-       GPU Driver: Dell TigerLake-LP GT2 [Iris Xe Graphics] [1028:09ff 
   `/ossssso+/:-        -:/+osssso+-     CPU Usage: 3% 
  `+sso+:-`                 `.-/+oso:    Disk (/): 86G / 251G (36%) 
 `++:.                           `-/+/   Locale: C.UTF-8 
 .`                                 `/
```

**Comment by Joshua169** [comment]
![{2498-x-11948723364367}](https://github.com/qier222/YesPlayMusic/assets/48385019/a7af83dd-f7e7-433a-869c-abbe57e444a8)
我也遇到这个问题，系统是ubuntu22.04.4 lts ，软件版本是4.8.2，[yesplaymusic_0.4.8_amd64.deb](https://github.com/qier222/YesPlayMusic/releases/download/v0.4.8-2/yesplaymusic_0.4.8_amd64.deb)
