### ISSUE TITLE
打开客户端报错，小白一枚也不太懂

### ISSUE THREAD

**Issue by RainHoutas** [qier222/YesPlayMusic#2267]
客户端，win11
![image](https://github.com/qier222/YesPlayMusic/assets/97776439/7ef628ea-8cb8-4ec4-ad8c-4e6b2f36f670)

Error
×
A JavaScript error occurred in the main process
Uncaught Exception:
Error:listen EACCES:permission denied 0.0.0.0:10754
at Server.setupListenHandle [as listen2](net.js:1301:21)
at listenlnCluster(net.js:1366:12)
at Server.listen (net.js:1452:7)
at Function.listen(C:\Program
Files\YesPlayMusic\resources\app.asar\node_modules\express\lib\application.js:635...
at Object.<anonymous>(C:\Program
Files\YesPlayMusic\resources\app.asar\background.js:2:1141708)
at Generator.next(<anonymous>)
at n(C:\Program Files\YesPlayMusic\resources\app.asar\background.js:2:1138642)
at processTicksAndRejections(internal/process/task_queues js:93:5)
确定

**Comment by Emin017** [comment]
我在linux上也遇到了这个问题：
![image](https://github.com/qier222/YesPlayMusic/assets/99674037/c9064a9c-f7c9-4c10-a573-20b3ec309d31)

**Comment by xuan-ish3** [comment]
可以先下载单程序版 然后再下setup安装 我是这样整好的

**Comment by RainHoutas** [comment]
> 可以先下载单程序版 然后再下setup安装 我是这样整好的

感谢，最近没遇见了，出问题了我去试试 :>
