### ISSUE TITLE
A JavaScripts error occurred in the main process

### ISSUE THREAD

**Issue by Emin017** [qier222/YesPlayMusic#2270]
# A JavaScripts error occurred in the main process
打开客户端后报错：
![image](https://github.com/qier222/YesPlayMusic/assets/99674037/1c1e66d7-c11d-49a5-9caf-76edf44de5ce)
```
ErrorAJavaScripterroroccurredinthemainprocess  UncaughtException: 
Error:Triedtowrite a messageto a closedstream
at EventEmitter.g.on.t.message(/opt/YesPlayMusic/resources/app.asar/  background.js:2:3342978)  
at e.exports.send(/opt/YesPlayMusic/resources/app.asar/background.js:  2:3305286)  
at EventEmitter.n(/opt/YesPlayMusic/resources/app.asar/background.js  2:3313142)  
at EventEmitter.emit(events.js:315:20) 
at F.t.descriptor.value(/opt/YesPlayMusic/resources/app.asar/  background.js:2:543821  
at u.seeked(/opt/YesPlayMusic/resources/app.asar/background.js:  2:3534562)  
at IpcMainlmpl.<anonymous>(/opt/YesPlayMusic/resources/app.asar  background.js:2:3611672)  
at IpcMainlmpl.emit(events.js:315:20) 
at Object.<anonymous>(electron/js2c/browser_init.js:161:9492) 
at Object.emit(events.js:315:20) 
```

### 反馈 bug 需要的信息

- linux客户端
- `Linux archlinux 6.9.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000 x86_64 GNU/Linux`

**Comment by Sh1tWu** [comment]
我也遇到了同样的问题，不过是点击歌曲播放之后，而且点击确认和取消都无法关闭弹窗
![屏幕截图_20240703_204658](https://github.com/qier222/YesPlayMusic/assets/93087648/4aed7bae-589f-4882-b560-c92d6df7f786)

**Comment by Emin017** [comment]
> 我也遇到了同样的问题，不过是点击歌曲播放之后，而且点击确认和取消都无法关闭弹窗 ![屏幕截图_20240703_204658](https://private-user-images.githubusercontent.com/93087648/345426489-4aed7bae-589f-4882-b560-c92d6df7f786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM4MjMsIm5iZiI6MTcyMDAxMzUyMywicGF0aCI6Ii85MzA4NzY0OC8zNDU0MjY0ODktNGFlZDdiYWUtNTg5Zi00ODgyLWI1NjAtYzkyZDZkZjdmNzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEzMzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZWU4ZjEzZGRjMWQ4YjhmMTI5MzRlNWY2ZmU4OGUxZDhhNTUwZmE3NzQ3ODhkYTcyYTVmZGM3MzE2YWY2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOYC-HmE-uDuyuGosc_m4TB928PKsBwuVSNW9RDaWUE)

我也是，而且还会反复弹出来，得手动kill掉整个软件的进程

**Comment by ZhouShaoyang** [comment]
遇到相同的问题

**Comment by ZhouShaoyang** [comment]
回退到0.4.7版本，退出登陆并清理缓存，再重新登陆后可解决。
