### ISSUE TITLE
mac 最新版还是没有办法 like

### ISSUE THREAD

**Issue by Elliot-hao** [qier222/YesPlayMusic#411]
![Uploading Screen Shot 2021-03-14 at 1.02.23 PM.png…]()

**Comment by Elliot-hao** [comment]
![Screen Shot 2021-03-14 at 1 02 47 PM](https://user-images.githubusercontent.com/30925823/111057875-95b4a600-84c5-11eb-8088-38a397808d30.png)

**Comment by llovvoll** [comment]
昨晚我有遇到同樣的問題，但是今早就正常了....可能是网易云造成的一些限制

**Comment by pxz666** [comment]
我也相同问题

**Comment by Indexyz** [comment]
MacOS 11.2.1, Brew 安装的 0.3.4 版本

请求 `http://localhost:27232/api/like?id=ID&like=true&timestamp=TS&cookie=COOKIE` 时发生 500 错误

```
TypeError: (intermediate value).then is not a function
    at /like (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/background.js:2:299199)
    at Layer.handle [as handle_request] (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:317:13)
    at /Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at x (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/background.js:2:1006437)
    at h (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/background.js:2:1010621)
    at Layer.handle [as handle_request] (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/YesPlayMusic.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:317:13)
```

**Comment by qier222** [comment]
v0.3.5 版本确认已经修复了
