### ISSUE TITLE
完善最小化到托盘功能

### ISSUE THREAD

**Issue by AniYPc421** [qier222/YesPlayMusic#523]
### 基本信息
客户端v0.3.5 于 Debian Buster
Linux 内核：4.19.181-1
桌面环境：GNOME 3.30.2
***
### 问题描述
选中 "Minimize to tray" 后点击关闭按钮后，程序仍然关闭，不会最小化到托盘。
看其他 issue 了解应该是点击最小化后就能实现。
看样子在 Windows 中可以实现，但在 GNOME 环境下这玩意开了当作没开，Alt+Tab 照样能切到，我还看到有个 issue 用的 Arch+i3wm ，平铺环境下这个功能更没用了，最小化按钮都找不到。虽然说移到其他工作区能解决，但还是希望做的跟云音乐差不多，点个叉叉退到托盘比较好。

输出：
```bash
$ yesplaymusic 
initializing
creating express app
(node:5758) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `yesplaymusic --trace-deprecation ...` to show where the warning was created)
server running @ http://127.0.0.1:10754
app ready event
creating app window
APPIMAGE env is not defined, current application is not an AppImage
(node:5758) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:5758) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setMenu' of undefined
    at App.<anonymous> (/opt/YesPlayMusic/resources/app.asar/background.js:2:2097457)
    at App.emit (events.js:315:20)
(node:5758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5758) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5758) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.s (/opt/YesPlayMusic/resources/app.asar/background.js:2:1961915)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:5758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
windows ready-to-show event
...some cookies...
windows close event
windows close event
$ 
```
动图：
![output](https://user-images.githubusercontent.com/44309752/113500166-7520be80-954e-11eb-81ff-270424ce42dd.gif)
***
### 再插一嘴
托盘图标在 GNOME 里面很糊，跟主程序颜值格格不入...
图片上看不出啥，但实际看得时候确实发虚
其他都做的挺好的，想提的其他 issue 也提到了，继续加油！！！\_(:3」∠)_
![Screenshot from 2021-04-04 13-09-46](https://user-images.githubusercontent.com/44309752/113500256-10b22f00-954f-11eb-98d9-d104fd05c468.png)

**Comment by 1478zhcy** [comment]
fedora下的gnome41没有问题
