### ISSUE TITLE
使用自签名证书SSL解密的时候netease_api 会报错

### ISSUE THREAD

**Issue by tywtyw2002** [qier222/YesPlayMusic#654]
自签名证书SSL解密的时候netease_api 会报错。  

```
[ERR] /mv/sublist?timestamp=1620370935348 {
  status: 502,
  body: {
    code: 502,
    msg: Error: self signed certificate in certificate chain
        at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket._finishInit (_tls_wrap.js:932:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
      code: 'SELF_SIGNED_CERT_IN_CHAIN',
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function (anonymous)]
    }
  }
}
```

chrome浏览器可以通过信任根证书解决问题。
![Screen Shot 2021-05-07 at 1 09 53 ](https://user-images.githubusercontent.com/576954/117411921-61f86a00-aed1-11eb-98f2-c479f6381ee3.png)

建议修改 `netease_api` 忽略ssl证书错误

```
diff --git a/netease_api/util/request.js b/netease_api/util/request.js
index b15d694..7b4f45a 100644
--- a/netease_api/util/request.js
+++ b/netease_api/util/request.js
@@ -117,7 +117,7 @@ const createRequest = (method, url, data, options) => {
       headers: headers,
       data: queryString.stringify(data),
       httpAgent: new http.Agent({ keepAlive: true }),
-      httpsAgent: new https.Agent({ keepAlive: true }),
+      httpsAgent: new https.Agent({ keepAlive: true, rejectUnauthorized: false }),
     }

     if (options.crypto === 'eapi') settings.encoding = null
```

**Comment by qier222** [comment]
是网页端吗？
