### ISSUE TITLE
无法播放音乐云盘歌曲

### ISSUE THREAD

**Issue by Blackjack200** [qier222/YesPlayMusic#720]
# 我已尝试
1. resetApp()后重新登陆
2. 重启进程
3. 打开debug控制台
4. 在issues搜索我要提出的问题

# 环境
设备: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
系统: MacOS Catalina 10.15.7 (19H1030)
CPU: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
软件版本: https://github.com/qier222/YesPlayMusic/releases/download/v0.3.9/YesPlayMusic-mac-0.3.9.dmg

# 复现方法
播放任意音乐(非云盘歌曲)
不暂停，直接播放云盘歌曲

# 错误信息
## 控制台输出
```log
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at h (app://./js/index.6daf10f2.js:1:121596)
    at app://./js/index.6daf10f2.js:1:26890
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27495)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26465)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at m (app://./js/index.6daf10f2.js:1:122003)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Object.t.get (app://./js/chunk-vendors.ef0759f9.js:45:69374)
    at m (app://./js/index.6daf10f2.js:1:121988)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Ce (app://./js/chunk-vendors.ef0759f9.js:45:67857)
    at Object.t._trans (app://./js/chunk-vendors.ef0759f9.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.ef0759f9.js:45:69254)
    at m (app://./js/index.6daf10f2.js:1:121988)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at Object.t._promise (app://./js/chunk-vendors.ef0759f9.js:45:93091)
    at Ce (app://./js/chunk-vendors.ef0759f9.js:45:67776)
    at Object.t._trans (app://./js/chunk-vendors.ef0759f9.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.ef0759f9.js:45:69254)
    at m (app://./js/index.6daf10f2.js:1:121988)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
```
## 完整导出
```log
DevTools failed to load SourceMap: Could not parse content for app://./js/index.6daf10f2.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-vendors.ef0759f9.js.map: Unexpected end of JSON input
index.6daf10f2.js:1 如出现问题，可尝试在本页输入 resetApp() 然后按回车重置应用。
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-45667e2a.3bd08c5e.js.map: Unexpected end of JSON input
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
(anonymous) @ electron/js2c/renderer_init.js:85
./lib/renderer/api/remote.ts @ electron/js2c/renderer_init.js:85
__webpack_require__ @ electron/js2c/renderer_init.js:1
loader @ electron/js2c/renderer_init.js:77
(anonymous) @ electron/js2c/renderer_init.js:25
(anonymous) @ chunk-235af1b4.5118c0d5.js:1
7381 @ chunk-235af1b4.5118c0d5.js:1
c @ index.6daf10f2.js:1
a0b9 @ chunk-235af1b4.5118c0d5.js:1
c @ index.6daf10f2.js:1
Promise.then (async)
component @ index.6daf10f2.js:1
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
Xt @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
h @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ index.6daf10f2.js:1
h @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
Ft @ chunk-vendors.ef0759f9.js:50
ee.confirmTransition @ chunk-vendors.ef0759f9.js:50
ee.transitionTo @ chunk-vendors.ef0759f9.js:50
e.push @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
we.push @ chunk-vendors.ef0759f9.js:50
ve.a.push @ index.6daf10f2.js:1
toLogin @ index.6daf10f2.js:1
re @ chunk-vendors.ef0759f9.js:32
n @ chunk-vendors.ef0759f9.js:32
i._wrapper @ chunk-vendors.ef0759f9.js:32
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-235af1b4.5118c0d5.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-9f6ad316.b062a95e.js.map: Unexpected end of JSON input
chunk-vendors.ef0759f9.js:62 POST http://localhost:27232/api/daily_signin?type=0&timestamp=1622250025535 400 (Bad Request)
(anonymous) @ chunk-vendors.ef0759f9.js:62
t.exports @ chunk-vendors.ef0759f9.js:62
t.exports @ chunk-vendors.ef0759f9.js:45
Promise.then (async)
u.request @ chunk-vendors.ef0759f9.js:1
(anonymous) @ chunk-vendors.ef0759f9.js:1
s @ index.6daf10f2.js:1
m @ index.6daf10f2.js:1
activated @ chunk-9f6ad316.b062a95e.js:1
re @ chunk-vendors.ef0759f9.js:32
Bn @ chunk-vendors.ef0759f9.js:32
Fn @ chunk-vendors.ef0759f9.js:32
tr @ chunk-vendors.ef0759f9.js:32
Jn @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:32
le @ chunk-vendors.ef0759f9.js:32
Promise.then (async)
ae @ chunk-vendors.ef0759f9.js:32
ve @ chunk-vendors.ef0759f9.js:32
er @ chunk-vendors.ef0759f9.js:32
rr.update @ chunk-vendors.ef0759f9.js:32
yt.notify @ chunk-vendors.ef0759f9.js:32
set @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
ee.updateRoute @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
Ft @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
Promise.then (async)
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
Xt @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
h @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
(anonymous) @ index.6daf10f2.js:1
h @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
r @ chunk-vendors.ef0759f9.js:50
Ft @ chunk-vendors.ef0759f9.js:50
ee.confirmTransition @ chunk-vendors.ef0759f9.js:50
ee.transitionTo @ chunk-vendors.ef0759f9.js:50
e.push @ chunk-vendors.ef0759f9.js:50
(anonymous) @ chunk-vendors.ef0759f9.js:50
we.push @ chunk-vendors.ef0759f9.js:50
ve.a.push @ index.6daf10f2.js:1
(anonymous) @ chunk-235af1b4.5118c0d5.js:1
Promise.then (async)
handleLoginResponse @ chunk-235af1b4.5118c0d5.js:1
Promise.then (async)
login @ chunk-235af1b4.5118c0d5.js:1
keyup @ chunk-235af1b4.5118c0d5.js:1
re @ chunk-vendors.ef0759f9.js:32
n @ chunk-vendors.ef0759f9.js:32
i._wrapper @ chunk-vendors.ef0759f9.js:32
undefined:1 GET http://localhost:27232/undefined?param=1024y1024 404 (Not Found)
Image (async)
qo @ chunk-vendors.ef0759f9.js:32
Vo @ chunk-vendors.ef0759f9.js:32
Ho @ chunk-vendors.ef0759f9.js:32
w @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
b @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
b @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
b @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
b @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
b @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:32
Mn.t._update @ chunk-vendors.ef0759f9.js:32
r @ chunk-vendors.ef0759f9.js:32
rr.get @ chunk-vendors.ef0759f9.js:32
rr @ chunk-vendors.ef0759f9.js:32
Dn @ chunk-vendors.ef0759f9.js:32
Or.$mount @ chunk-vendors.ef0759f9.js:32
init @ chunk-vendors.ef0759f9.js:32
h @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:32
Mn.t._update @ chunk-vendors.ef0759f9.js:32
r @ chunk-vendors.ef0759f9.js:32
rr.get @ chunk-vendors.ef0759f9.js:32
rr @ chunk-vendors.ef0759f9.js:32
Dn @ chunk-vendors.ef0759f9.js:32
Or.$mount @ chunk-vendors.ef0759f9.js:32
init @ chunk-vendors.ef0759f9.js:32
h @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:32
Mn.t._update @ chunk-vendors.ef0759f9.js:32
r @ chunk-vendors.ef0759f9.js:32
rr.get @ chunk-vendors.ef0759f9.js:32
rr @ chunk-vendors.ef0759f9.js:32
Dn @ chunk-vendors.ef0759f9.js:32
Or.$mount @ chunk-vendors.ef0759f9.js:32
init @ chunk-vendors.ef0759f9.js:32
h @ chunk-vendors.ef0759f9.js:32
p @ chunk-vendors.ef0759f9.js:32
E @ chunk-vendors.ef0759f9.js:32
T @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:32
Mn.t._update @ chunk-vendors.ef0759f9.js:32
r @ chunk-vendors.ef0759f9.js:32
rr.get @ chunk-vendors.ef0759f9.js:32
rr.run @ chunk-vendors.ef0759f9.js:32
Jn @ chunk-vendors.ef0759f9.js:32
(anonymous) @ chunk-vendors.ef0759f9.js:32
le @ chunk-vendors.ef0759f9.js:32
Promise.then (async)
ae @ chunk-vendors.ef0759f9.js:32
ve @ chunk-vendors.ef0759f9.js:32
er @ chunk-vendors.ef0759f9.js:32
rr.update @ chunk-vendors.ef0759f9.js:32
yt.notify @ chunk-vendors.ef0759f9.js:32
set @ chunk-vendors.ef0759f9.js:32
set @ index.6daf10f2.js:1
value @ index.6daf10f2.js:1
(anonymous) @ index.6daf10f2.js:1
Promise.then (async)
value @ index.6daf10f2.js:1
play @ chunk-45667e2a.3bd08c5e.js:1
click @ chunk-45667e2a.3bd08c5e.js:1
re @ chunk-vendors.ef0759f9.js:32
n @ chunk-vendors.ef0759f9.js:32
i._wrapper @ chunk-vendors.ef0759f9.js:32
Show 25 more frames
index.6daf10f2.js:1 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at h (app://./js/index.6daf10f2.js:1:121596)
    at app://./js/index.6daf10f2.js:1:26890
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27495)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26465)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at m (app://./js/index.6daf10f2.js:1:122003)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Object.t.get (app://./js/chunk-vendors.ef0759f9.js:45:69374)
    at m (app://./js/index.6daf10f2.js:1:121988)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at qt.n (app://./js/chunk-vendors.ef0759f9.js:45:59720)
    at Ce (app://./js/chunk-vendors.ef0759f9.js:45:67857)
    at Object.t._trans (app://./js/chunk-vendors.ef0759f9.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.ef0759f9.js:45:69254)
    at m (app://./js/index.6daf10f2.js:1:121988)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
From previous: 
    at Object.t._promise (app://./js/chunk-vendors.ef0759f9.js:45:93091)
    at Ce (app://./js/chunk-vendors.ef0759f9.js:45:67776)
    at Object.t._trans (app://./js/chunk-vendors.ef0759f9.js:45:69106)
    at Object.t.get (app://./js/chunk-vendors.ef0759f9.js:45:69254)
    at m (app://./js/index.6daf10f2.js:1:121988)
    at Proxy.value (app://./js/index.6daf10f2.js:1:26461)
    at Proxy.value (app://./js/index.6daf10f2.js:1:27456)
    at app://./js/index.6daf10f2.js:1:28095
h @ index.6daf10f2.js:1
(anonymous) @ index.6daf10f2.js:1
Promise.then (async)
(anonymous) @ chunk-vendors.ef0759f9.js:45
$t @ chunk-vendors.ef0759f9.js:45
Xt @ chunk-vendors.ef0759f9.js:45
Yt @ chunk-vendors.ef0759f9.js:45
Gt @ chunk-vendors.ef0759f9.js:45
Xt @ chunk-vendors.ef0759f9.js:45
Yt @ chunk-vendors.ef0759f9.js:45
Gt @ chunk-vendors.ef0759f9.js:45
Xt @ chunk-vendors.ef0759f9.js:45
Yt @ chunk-vendors.ef0759f9.js:45
Gt @ chunk-vendors.ef0759f9.js:45
Promise.then (async)
(anonymous) @ chunk-vendors.ef0759f9.js:45
Wt @ chunk-vendors.ef0759f9.js:45
(anonymous) @ chunk-vendors.ef0759f9.js:45
Jt @ chunk-vendors.ef0759f9.js:45
ne @ chunk-vendors.ef0759f9.js:45
(anonymous) @ chunk-vendors.ef0759f9.js:45
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-a53cf188.ebafe37e.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for app://./js/chunk-3c4730d8.4b4d2cd8.js.map: Unexpected end of JSON input
```

**Comment by wjw233** [comment]
我可以诶

**Comment by Blackjack200** [comment]
播放任意音乐(非云盘歌曲)
不暂停，直接播放歌单内云盘歌曲(我是第一首为云盘歌曲)
