### ISSUE TITLE
opensuse leap15.3无法加载页面

### ISSUE THREAD

**Issue by Elegantid** [qier222/YesPlayMusic#866]
```
le@openSUSE:~/下载> '/home/le/下载/YesPlayMusic-0.4.0.AppImage' 
[background.js] initializing
[background.js] creating express app
(node:5887) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `yesplaymusic --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: getaddrinfo ENOTFOUND openSUSE
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
Checking for update
(node:5887) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:5887) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setMenu' of undefined
    at App.<anonymous> (/tmp/.mount_YesPlaHGE6Kk/resources/app.asar/background.js:2:2248243)
    at App.emit (events.js:315:20)
(node:5887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5887) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.s (/tmp/.mount_YesPlaHGE6Kk/resources/app.asar/background.js:2:2106646)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:5887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[background.js] windows ready-to-show event
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: connect ECONNREFUSED 127.0.0.1:10754
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Update for version 0.4.0 is not available (latest version: 0.4.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[background.js] windows close event
[background.js] windows close event
le@openSUSE:~/下载> 
```

**Comment by pan93412** [comment]
應是暫時性問題。
