### ISSUE TITLE
Bug: 启动时报错 EACCES permission denied

### ISSUE THREAD

**Issue by 5ME** [qier222/YesPlayMusic#899]
- Windows 免安装客户端 0.4.0
- 系统版本：Windows 10 21H1

启动时报错：`A JavaScript error occurred in the main process`

如图所示：

![启动报错](https://gitee.com/ME_WE/my-picture-repository/raw/master/%E9%9B%B6%E7%A2%8E/Yes%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%BC%82%E5%B8%B8.png)

**Comment by dreistein543** [comment]
版本：macos-arm64.dmg
系统版本：macOS Big Sur 11.5.2 （M1芯片）
安装渠道：homebrew  &  github手动下载安装
启动时报错：app文件已损坏

另： 直接打开dmg文件，直接双击打开.app文件存在相同报错；安装universal版本可以正常启动

**Comment by Mini-suger** [comment]
安装yt-dlp,之后好像就不报错了

**Comment by aboutZZ** [comment]
使用的最新版 0.4.6， 我也遇到同样的问题了
```log
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: listen EACCES: permission denied 0.0.0.0:35216
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (C:\Program Files\YesPlayMusic\resources\app.asar\node_modules\express\lib\application.js:635:24)
    at Object.serveNcmApi (C:\Program Files\YesPlayMusic\resources\app.asar\background.js:2:889608)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Program Files\YesPlayMusic\resources\app.asar\background.js:2:2515805

[确定]
```

**Comment by hugo-sama** [comment]
有个 workaround 是让Windows绕开 10754 端口的占用
希望能在设置里手动指定端口

**Comment by Sisyphean-a** [comment]
我遇见了同样的问题，但是端口并没有被占用：
![image](https://github.com/qier222/YesPlayMusic/assets/59257340/7c2fa4c2-db7f-4ea6-9cd5-8c8f5b892bea)

**Comment by ghhccghk** [comment]
这个原因可能是端口被 Hyper-V 随机保留（占用）

解决方法可以看这个https://zhuanlan.zhihu.com/p/474392069
